### ISSUE TITLE
Does not work on Plex

### ISSUE THREAD

**Issue by einarhg** [dvlden/ultrawideo#10]
The extension does not interact with the video in the Plex webapp https://plex.tv . It works fine with Youtube on both browsers I tried.

I'd be happy to provide access to my Plex server for testing if you don't have access to one.

### Environment
- **OS**: Windows 10 1803
- **Browser**: Chrome74.0.3729.169  and Opera 60.0.3255.151

**Comment by dvlden** [comment]
Hello @einarhg,

Thank you for reporting this.
It's unfortunate, but I do not have access to this... I noticed 90 days free trial, but it's not available in my country.

If you are willing to provide me your credentials for testing and debugging, I'd be happy to improve my extension if it's not something related to their development, but mine.

You can e-mail me on: n.dvlden@gmail.com

<img width="596" alt="Screen Shot 2019-06-11 at 9 31 03 PM" src="https://user-images.githubusercontent.com/3460368/59300753-4017ed80-8c90-11e9-9f88-e9a4dc124a89.png">

**Comment by einarhg** [comment]
Hi.

I just sent you an invite.
I have been using a very similar Chrome plugin called UltraWide Video which
works perfectly with Plex.
I'm trying out Opera and stumbled on your plugin.

**Comment by dvlden** [comment]
Hello, 
Thanks for the invitation. Had to subscribe to get access to it...

Will test now and come with conclusion very soon.

**Comment by dvlden** [comment]
After 30 minutes of debugging, I was able to figure out two things.

1. The UltraWideo classes are being added, but then immediately stripped-off. 
- I thought that they may be watching for any kind of DOM changes and then restore to original, which would be crazy... So I considered this right away as "most likely not being the case" and it's correct.

[Log 1](http://drop.dvl.sh/A0hpNI)

2. The fullscreen event on their platform is triggered twice, instead of once.
- It's not the bug on UltraWideo end, but rather on their end.

[Log 2](http://drop.dvl.sh/jKaewy)

In the end, I was able to figure out that the problem is that they listen for both `fullscreenchange` and `webkitfullscreenchange` events, which are registered on UltraWideo.

Why does UltraWideo listen to both events and not just one?
Well, there's one very fuc*ed up reason that I'm not willing to explain in detail right now, but I can just say that it is very important for some video players, especially the embedded/iFramed ones.

I cannot check what listener does browser support, because webkit supports both and because they use both for these specific cases. One triggers for non-embedded, the other triggers for embedded. Very mind fuc*ing, but it's the truth. 

What I can do? Nothing... What you can do? Contact them to listen only to the event that browser supports. It's simple fix for them and impossible one for me.

**Comment by dvlden** [comment]
**Update:**
Been going through some video streaming platforms... Just checked Plex and it appears to be working.
So it seems like they fixed this duplicate event issue.

**Comment by dvlden** [comment]
**Update:**
Seems like they broke it again. Marked with `nofix`.
