### ISSUE TITLE
Custom upscale level

### ISSUE THREAD

**Issue by MaluNoPeleke** [dvlden/ultrawideo#106]
When watching 16:9 videos on a 21:9 with upscale enabled crops off quite a lot of content.
It would be nice to define the level of upscaling.
As an example I could image to crop a 16:9 video to 19:9 in fullscreen and have small black borders.

**Comment by MCCP335** [comment]
Exactly, this or just having an option where the extension zooms into the content so that the black bars only appear on two sides.
This would keep the original aspect ratio of the content without any horrid stretching and wouldn't crop out and lose any of it.
For example, on disney+ you have to choose between huge bars all around your content or loosing a noticable bit at the top and bottom. This would be fixed

**Comment by dvlden** [comment]
This is definitely going to be in the v3.

<img width="468" alt="Screenshot 2023-10-25 at 23 05 56" src="https://github.com/dvlden/ultrawideo/assets/3460368/3dc5e3ce-f234-44b2-809b-4040cf1276cc">
