### ISSUE TITLE
Does not work on ver.movistarplus.es

### ISSUE THREAD

**Issue by dmnmsc** [dvlden/ultrawideo#12]
Hi!

The extension does nothing at ver.movistarplus.es. 

You can test yourself after installing the extension needed to play videos there.

**Comment by dvlden** [comment]
How do I use this website?

http://drop.dvl.sh/2kZf5p

It does not appear to be working at all, even after installing their Chrome extension.

**Comment by dmnmsc** [comment]
> 
> 
> How do I use this website?
> 
> http://drop.dvl.sh/2kZf5p
> 
> It does not appear to be working at all, even after installing their Chrome extension.

hmmm... That's a generic error code. But I'm trying to play the same video connected to a VPN and I have the same error as well when using countries outside Europe.

**Comment by dvlden** [comment]
Okay, I'll try to get an VPN today and see what I can do.

**Comment by dvlden** [comment]
Hello... I investigated this further. 

Apparently they are using HTML Custom Elements to build their custom video player.
The UltraWideo extension doesn't know anything about it, hence when fullscreen occurs - it returns `undefined`.

<img width="599" alt="Screen Shot 2019-06-17 at 6 50 06 PM" src="https://user-images.githubusercontent.com/3460368/59622090-f49e8d00-9130-11e9-9777-589464458b4b.png">

This is not doable from my end, because I can't assume that `any` element is video player. Only `video` elements are valid and recognized by this extension.

**Comment by dmnmsc** [comment]
Oh, that's sad. But thank you very much for your time and explanation!

**Comment by dvlden** [comment]
Yes it is, indeed. 
You're welcome. I better make a list in README file for sites where it is known that this extension does not work.

Thank you for your report.

**Comment by dmnmsc** [comment]
Hey, I was thinking about this issue and I found something. There is an extension called [Ultra Wide Video ](https://github.com/wltrsjames/Ultrawide-Video) for Microsoft Edge which seems to do the job. Maybe you can find something useful there? It's an open source project developed by wltrsjames.

**Comment by dvlden** [comment]
Hello @dmnmsc,

I'm aware of this extension, but they are built with very different approaches. 
Aside, the extension you linked me to is listening to `webkitfullscreenchange` event only. 

Which means, it does not work for embedded videos. 

I'll be testing if such browser bug still exists. If it is fixed, I'll remove one of the events, such as `webkitfullscreenchange` and extension should be working on this site too. 

But if browser bug still exists, I can't remove the event, because embedded videos are highly used.
