### ISSUE TITLE
It does not work on Disney+

### ISSUE THREAD

**Issue by dvlden** [dvlden/ultrawideo#24]
### Describe the bug
Reported by a user of the extension on Mozilla.
https://addons.mozilla.org/en-US/firefox/addon/ultrawideo/reviews/1467188/

No details, nor environment were provided, but it probably does not work for any device on every video of their platform.

---

I am kindly asking every Disney Plus member out there that are using Ultrawideo extension, to provide me their authentication details on my e-mail address. Also tell me for which region is it... _(I just need one, so if you send it to me, leave a comment, so that the others do not do it as well)_

`n.dvlden@gmail.com`

If I do not manage to get the credentials for this platform, as I was unable to get it for the Amazon Prime, this bug will never be fixed.

**Comment by mcelrath** [comment]
Removing `position: absolute` in `styles/inject.css` seems to fix it. (Also tested this on Netflix, YouTube, and Amazon Prime and it works).

**Comment by dvlden** [comment]
@mcelrath - Thank you for your submission and research. 

I've been having issues on some other platforms, where `position` is not set. That's why I have to force it and apply `t/r/b/l` to `0` as well.

Just like on DailyMotion, I think the best approach for Disney+ is to remove all properties from one of the parent containers, where "they" usually do something weird.

I was able to get Disney Plus yesterday _(so great timing @mcelrath)_, and I found that they have a parent `.hudson-container`, where I can remove all properties and everything goes back in order.

---

I honestly hate all these platform-specific issues with the styles, but hopefully, I get the account credentials for each issue report, so that I can quickly resolve the issue.

**Comment by mcelrath** [comment]
Yeah you'd think they could just write their own CSS correctly to handle this... :-/

I'm on Linux/Firefox, with a 3840x1600 monitor (21:9 but need scaling).

Ping me if you want me to test anything, for now I have to load my hacked-up ultrawidevideo.xpi using the debug screen unless I figure out how to build your code. ;-)

**Comment by dvlden** [comment]
@mcelrath - Every platform could make their video players adopt to any resolution. It can be even more powerful if they have two or more different aspect ratios exported and depending on the resolution of the screen, they could serve proper export for that ratio.

Unfortunately, I do not see any of that coming to any video streaming platforms, at least not now. 

---

I'd appreciate if you can look for `2.1.0` release on Firefox and test if it works on Disney+ as well as on some other streaming platforms (that you personally use)

If you can report back here, it'd be really helpful!

**Comment by mcelrath** [comment]
2.1.0 feedback on a 21:9, 3840x1600 monitor:

Note, I want "make the content as big as possible preserving the aspect ratio". I think the three sliders Normal/Upscale/Stretch can be reduced to two or    zero: "preserve aspect ratio" and "fill screen with no black bars, even if it changes the aspect ratio". I don't think anyone wants the latter and to watch  people with squished heads though, but the difference between 16:9 and 21:9 is probably difficult to notice for many people.

Now there's a problem with content that has black bars encoded into it. (e.g. 16:9 content encoded for 4:3 screens, or 21:9 content encoded for 16:9         screens) There's a lot of this out there. Without access to the source material due to DRM dumpster fire-ness, I can't tell if this is the case on any given video. :-/

I'm interpreting the following desired behavior (correct me if I'm wrong).

21:9 content: all three modes should behave identically, filling the screen.

16:9 and 4:3 content: "Normal" should preserve aspect ratio, filling the screen vertically with black bars on the sides. "Upscale" should fill the screen    horizontally, cutting off material at the top and bottom. "Stretch" should fill the screen, not cutting off any content but distorting the aspect ratio.     Below I record only **deviations** from this behavior.

I suggest a change in these modes, as "Upscale" and "Stretch" are ambiguous:

1. "Normal" (best guess)
2. "Fill horizontally" (aspect ratio preserving)
3. "Fill vertically" (aspect ratio preserving)
4. "Zoom" (fill screen, changing aspect ratio)

#2,3 may cut off content if the aspect ratio of your monitor doesn't match the source material. These options 2,3 are hopefully more intuitive for content   with encoded black bars.

If people are using this plugin with 16:9 or 4:3 monitors...god help them. There are too many permutations.

Again below is only recording **deviations** from the behavior described above.

Disney Plus:

21:9 content (Star Wars): "Normal" puts a black box on all sides. "Stretch" fills the screen horizontally but adds black bars on the top and bottom.
16:9 content (Avatar): "Upscale" cuts off the top and bottom.
4:3 content: (Steamboat Willie): "Upscale" and "Stretch" behave identically to "Normal". None of the three modes fills the screen with no black bars on the  sides.

Netflix:

21:9 content (Inception): "Stretch" fills screen horizontally and adds black bars on the top and bottom.
16:9 content (Altered Carbon): "Stretch" fills the screen horizontally with black bars at the top and bottom.
4:3 content: (The Twilight Zone): works as described in all three modes.

Amazon Prime:

21:9 content (Captain America): works as described in all three modes.
16:9 content (Eureka, S1): works as described in all three modes.
4:3 content (The Twilight Zone): works as described in all three modes.

Youtube:

[21:9 content](https://www.youtube.com/watch?v=oLl-d1RETXM) works as described in all three modes.
[16:9 content](https://www.youtube.com/watch?v=UG_Ks_wRTpo) works as described in all three modes.
[4:3 content](https://www.youtube.com/watch?v=yyPFT3Ajkzc) works as described in all three modes.

**Comment by dvlden** [comment]
@mcelrath I am amazed by your research and details.

> I'm interpreting the following desired behavior (correct me if I'm wrong).

The answer is hard. Because the extension is basically for any screen, not UW only. 
So the mode really depends on the content's aspect ratio and the screen resolution as well. They behave differently.

### My MacBook for example

It has **1366x768** resolution, playing your provided **16:9** YouTube content, by default has vertical black bars present. _**(talking fullscreen of course)**_

| Mode | Behaviour |
| --- | --- |
| Upscale | Zooms in the video, removing vertical black bars and cropping horizontal part of the video. |
| Stretch | It compacts the video (instead of stretching), filling vertical black bars and making it distorted as you described. |

Notice, no mention of the `Normal` mode? That's because the purpose of `Normal` is like the `Pause`, without actually killing the events. It does not affect any videos (in my experience), but from your testing, it seems like it does, while it shouldn't...

---

> I suggest a change in these modes, as "Upscale" and "Stretch" are ambiguous:

- "Normal" (best guess)
- "Fill horizontally" (aspect ratio preserving)
- "Fill vertically" (aspect ratio preserving)
- "Zoom" (fill the screen, changing aspect ratio)

Are you suggesting the name change? How would you best describe the 2nd and 3rd mode? "Fill" or "Preserve". Also, do you think that "Pause" should maybe not kill the keyboard events, but only other listeners? Then I could remove the "Normal" mode and people would use "Pause" when they want to kill the modifications. 

Do you think that these would be sufficient?

- Pause
- Fill
- Zoom
- Shortcut Config

---

I highly appreciate your research and I'll take a deeper look at it the next day. I want to test all of the mentioned content myself as well.

I am kind of bummed from my latest release (on Chrome Webstore). It is still pending manual review and God knows how long that'll take. Because I'm using `<all_urls>` as a matcher for `content_scripts`, which I obviously need as I can't only allow this to work on specific URLs, especially if I know that there would be embedded videos on many sites out there. 

> If any browser extension developers come across this comment, let me know if there's something i can do to get these approvals fast? (maybe there's a workaround, instead of using `content_scripts`, but I couldn't find anything)

**Comment by mcelrath** [comment]
If you intend this to work for any screen, you need to know:
1. aspect ratio and resolution of the user's screen
2. aspect ratio and (resolution?) of the content
3. whether the content encodes black bars on the top/bottom or sides

Can you determine (2)? If so then some logical choices can be made, up to (3) which I think is probably impossible to know.

FYI I don't know that users will know the difference between "Fill" and "Zoom" (I don't think I do). Here's a link with some definitions, but I don't think there is any standard definition, you'll probably need good tooltips. ;-)
https://support.renewedvision.com/hc/en-us/articles/360011694174-Media-Scaling-Options
