### ISSUE TITLE
32:9 Support

### ISSUE THREAD

**Issue by enterprise12nx** [dvlden/ultrawideo#25]
Why is 32:9 Not possible?
From what i can tell the extension works great, but not usable for 32:9 as the upscale feature cuts off some of the video on all sides.

**Comment by dvlden** [comment]
Well, I am on 3840×1080 resolution... Are you on 5120×1440? 
I can't test that, without buying that big of a screen, which costs money, which I don't have. Especially since the extension is totally free 👍 

Anyway, on 3840x1080, I don't mind the bits and pieces of cropped content, as long as I have a clear wide picture, with no black bars. 

It probably sucks on 5120x1440, but there's nothing that I can do.

**Comment by enterprise12nx** [comment]
Yes im 5120x1440
damn that sucks, there isnt a way you could try developing it and having me test and report back?

**Comment by dvlden** [comment]
I totally understand your frustration, using this extension, on that wide resolution.
Unfortunately, not. There's nothing that I can do in this particular case.
