### ISSUE TITLE
Enable us to use landscape without autorotate

### ISSUE THREAD

**Issue by ShalokShalom** [dvlden/ultrawideo#27]
I like to lay down in my bed, when watching movies.

In order to do so, I move my phone to the side, so it adjusts with the position of my head.

And in order to be able to do so, I need to disable auto-rotate, since my phone is not smart enough to understand this intention.

Your application does stuck in portrait mode here on Android Pie, when I do this.

I see less sense for an application like yours, to be stuck at portrait mode.

And if there is one, I would like to opt in that, instead of defaulting to it.

Is there anything you can do to use landscape mode in fullscreen, when my phone has the auto rotate feature disabled?

**Comment by dvlden** [comment]
Hello there,
I'm unsure if I completely understand the situation.

How do you make video full screen in portrait mode? 
When you make the video full screen, it should make it go forcefully to landscape mode? (I'll double-check this) 

If the video goes full screen in portrait mode, somehow, then I assume I also need to check for orientation change event (to cover mobile devices)

**Comment by ShalokShalom** [comment]
Yes, when the phone is detected as in portrait mode, it looks like this;

![Screenshot_2020-01-25-11-39-19-70_3aea4af51f236e4932235fdada7d1643](https://user-images.githubusercontent.com/6344099/73135056-4b146800-403e-11ea-85d2-e99db0af3c0b.png)

**Comment by dvlden** [comment]
I just checked this on my iPhone (without my extension, as iPhone already does that by default)

• When I play the video in portrait mode and tap the icon to make it `upscale` it actually does exactly what you are showing in the screenshot.

• If I rotate my device (with Portrait Orientation Lock – off), it will put the video into the landscape mode and I would see all the content.

I think I understand what you are requesting right now... (by reading the title of this issue)
You want to play the video in `landscape` orientation, even if the Portrait Orientation Lock on your device is enabled... 

I don't think that's possible, and it'd be annoying for people that actually don't want to do that since they have their orientation lock enabled.

Sorry @ShalokShalom, but thank you for the suggestion.

**Comment by ShalokShalom** [comment]
> I don't think that's possible

I think so long as there is an API, this is very simple.

> and it'd be annoying for people that actually don't want to do that since they have their orientation lock enabled.

Why should anybody would want this?

And this is also why I wrote:

> I see less sense for an application like yours, to be stuck at portrait mode.
> 
> And if there is one, I would like to opt in that, instead of defaulting to it.

It seems you barely use your app on the phone, so I ask you to use it like that:

https://media.istockphoto.com/photos/girl-using-smart-phone-and-lying-down-in-bed-picture-id891416516?s=170667a

You will very quickly understand, why this is so important.
