### ISSUE TITLE
Does Not Work On Twitch.tv

### ISSUE THREAD

**Issue by Kaizuen** [dvlden/ultrawideo#3]
I watch a lot of video game streams on a website called "Twitch.tv" and have previously been using a development version of an old (now defunct) Chrome Extension called "Ultrawide Video" which can be found here: https://github.com/wltrsjames/Ultrawide-Video/tree/develop 

I really like the sound of this extension, and that it is actively being updated, so I would really like to see it working on Twitch.tv as it is one of the website that I spend the most time watching video on. I'll leave some information about my setup down below.

OS: Windows 10
OS Version: 1809
Monitor: Acer XR382CQK
Browser: Google Chrome
Browser Version: 71.0.3573.0 (Official Build) dev (64-bit)

The issue I experienced is that the app simply did nothing at Twitch.tv. It had zero affect on any videos playing on the site no matter what mode I used. I tried restarting the browser, opening the web page with the Extension paused, etc. Nothing seemed to work.

If you have any questions / require any more troubleshooting, please let me know.

Thanks!

**Comment by dvlden** [comment]
Thank you for opening up an issue @Kaizuen.

I just looked into this and I noticed that Twitch have multiple "videos" loaded into the DOM. For some reason, all these videos are invisible and the one that is supposed to be connected with UltraWideo extension, just isn't. 

I'll try to find some time shortly to figure out, if there's anything I can do regarding this.

**Comment by dvlden** [comment]
I tested this on Twitch when you posted this issue and it wasn't working.
Now that I managed to get some spare time to look into this issue, it magically started working. 💥 

![screen shot 2018-10-12 at 8 40 32 pm](https://user-images.githubusercontent.com/3460368/46887845-1e473c00-ce5f-11e8-90b6-6671255e43eb.png)

As you can see from the screenshot, there are three VIDEO elements in this single DOM. 
Apparently the plugin is now working because the VIDEO element is now the first in the query list. The extension itself only gets the first video element in the DOM and sometimes on Twitch that is not the case. 

I noticed that all other VIDEO elements contain `[title]` attribute of "Advertisement". I made a quick fix in single method of the extension, to exclude the video elements that contain title attribute.

It should now be working, at least I'm hoping to see it working after this. 

I will push new version and update the package for all browsers.
