### ISSUE TITLE
Amazon Video not working

### ISSUE THREAD

**Issue by nexitem** [dvlden/ultrawideo#30]
Hey,

This isn't working on Opera with Amazon Video for me... I can possibly provide login credentials if you need them to figure out why.

**Comment by dvlden** [comment]
Hello,

I believe I have an Amazon Video account, laying around, so I will check it out.
I will test it from Chrome because it's the same engine in the end.

Stay tuned.

If you can leave me a link to the movie/show that you have troubles with specifically or if it's for everything out there? Please, do let me know.

**Comment by nexitem** [comment]
Well the new Star Trek Picard show did not work, but it has the format
that's perfect for it.

Am Do., 16. Apr. 2020 um 22:07 Uhr schrieb Nenad Novaković <
notifications@github.com>:

**Comment by dvlden** [comment]
Hello,

Thank you for a quick response back.
Unfortunately, I'm unable to reproduce this. I thought that it might be something different in Opera since I was testing from Chrome. However, it works in both browsers for me.

Is this the right platform?
[www.primevideo.com/detail/0TADTFDN6AK2XMC7HMLX0HFRPO](Star Trek: Picard)

From the screenshots provided below, I am confirming that it is working as expected.
The only time I am able to reproduce any issues with Amazon Prime is the first time I visit, after a while, and they throw some kind of advertisement at me. After watching the ad and reload, everything should work again. If you do not make the video fullscreen, while the ad is running, reload won't be necessary.

![Screen Shot 2020-04-16 at 22 54 51](https://user-images.githubusercontent.com/3460368/79505911-6ab39f00-8035-11ea-8c7c-0845db698d24.png)
![Screen Shot 2020-04-16 at 22 55 03](https://user-images.githubusercontent.com/3460368/79505929-7010e980-8035-11ea-8a23-24090c4f0188.png)

**Comment by nexitem** [comment]
Could it be that the german site does something different? Also, I cannot
even make screenshots of the website, it will be black If I try to do that.

for me it looks like this...
https://cdn.discordapp.com/attachments/471464469634088962/700081445690933248/IMG_20200415_223325.jpg

Am Do., 16. Apr. 2020 um 23:00 Uhr schrieb Nenad Novaković <
notifications@github.com>:

**Comment by dvlden** [comment]
You can't screen capture the video playback on Amazon Prime Video? 🤔
Yeah, by the photo you sent, it's pretty obvious that the extension doesn't do anything.

Hmmm, could you provide me your credentials? Because I have credentials for US and it seems like I'd need to subscribe again for DE version, which is pretty sad.

You can safely mail me at `nenad@dvl.sh`.

**Comment by nexitem** [comment]
I think I cannot capture it because of DRM protection. can I send you
credentials somewhere private?

Am Fr., 17. Apr. 2020 um 16:23 Uhr schrieb Nenad Novaković <
notifications@github.com>:

**Comment by nexitem** [comment]
I've sent you my login data, You will probably have to type in a code to
verify. You can contact on the mail I've sent you the login data from or
anywhere here:

[image: image.png]

>
