### ISSUE TITLE
[All] Remember settings for each site

### ISSUE THREAD

**Issue by jputting** [dvlden/ultrawideo#33]
Hi,

I would like to request that Ultrawideo has an option to remember aspect ratio preferences on a website basis.

It is a real pain in the neck to manually adjust the aspect ratio of websites that mainly feature older 4:9 aspect ratio videos each.

Every time I choose to visit the website and view videos, I have to adjust the aspect ratio and adjust it again when viewing each video in 4:9 aspect ratio.

The option to only have Ultrawideo active on chosen websites would still exist and a manual disabling option for individual videos could be made available.

**Comment by dvlden** [comment]
Hello @jputting,

I like this feature idea. Personally, I never had any problems hitting the shortcut a couple of times, when necessary, but my preference for all sites is always the "Upscale" mode.

I'll see what I can do. At the moment, I'm very busy with some 9-5 work, but as soon as I get some spare time, I'll get my hands on this. 

---

If someone who is using UltraWideo comes across this issue and is a developer who's willing to help with this feature request, please let me know here.

**Comment by hackerb9** [comment]
I'm using a 4:3 CRT to watch old 4:3 television content from Amazon Prime Video and (thanks to UltraWideo!) it works great. But I keep forgetting to turn it off and it lops off the edges for 16:9 content. (Is that what "upscale" is supposed to do?)

This feature request would solve the problem for me as the only 4:3 show I watch happens to be the only show I watch on amazon.com, so there's a one-to-one mapping between the site name and my preferences. (UltraWideo enabled only on amazon.com; paused elsewhere). 

However, I think it may be a good idea to use a pattern matching URL approach (preferably regular expressions) instead of only using the site name. That would allow people who watch several shows on a site to have separate preferences, if they felt like doing so. E.g., I'd store the preferences for "amazon.com/gp/video/detail/B07PNDDRKG/" as "unpause on load", but for other Amazon TV shows (which have different URLs), I'd leave it at the overall default, "paused".

I understand this may add complexity you do not wish to expose to the user, but I believe it will not be too bad. Here's how I imagine it working: When a user clicks on an obvious button to "Save site settings", the default can be to use only the current domain name. Hidden out of the way, perhaps by right-clicking on "Save site settings", can be another option: "Edit site matching pattern". That would be an advanced option which would fill in the entire URL of the current tab and let the user edit it as a regex, if they wish.

**Comment by dvlden** [comment]
Hey @hackerb9 ,

From your very descriptive comment I conclude that this feature would be either bad UX or headache for development.
My initial thought was to create this feature to be domain specific _(if enabled via new master switch)_ and I guess this should be fine for many users. But then again, not all videos are the same aspect ratio on a single platform. Unfortunately... 

I did not plan to make it `paused` by default, but just `normal` mode as default on all sites where settings were not touched.

Making it match entire URL would consume plenty of local storage memory and is not something I'd personally want to implement.
Since aspect ratio can't be detected - realistically, due to intentional black bars added in the rendered output, I can't specifically develop a feature that will work automatically with one setting for `4:3` AR, for example. 

I developed a package that rounds the aspect ratio to the common one, but that's still not enough, due to intentional black bars, as mentioned:
https://github.com/dvlden/aspecter

Adding regex config is also not something that I'd like this extension to have, as it creates complexity and many users of the extension are not developers.

--- 

And finally, yes, that's what upscale does.

**Comment by hackerb9** [comment]
I appreciate your charitable interpretation that my verbose description of bad UX is due to constraints imposed by this specific feature request. It is quite possible, however, that I am simply terrible at UX design and the feature is not to blame. Just for my edification, what was it that struck you as bad?

Please do continue with a domain only approach. I don't have any pressing need for the more complicated suggestion; I just thought it would make UltraWideo more useful.

> I did not plan to make it paused by default, but just normal mode as default on all sites where settings were not touched.

I was imagining that the master settings, as they already exist, would continue to function. So, I could just pause UltraWideo as usual to change the default. I would only have one site-specific setting:

    amazon.com    mode=normal

> Making it match entire URL would consume plenty of local storage memory and is not something I'd personally want to implement.

Perhaps I'm missing something. I thought the limit on local storage was around 10MB, no? Even if the limit was 10KB, it would suffice as we're talking about a file that has probably only one or two URLs. Worst case, someone might have dozens.  

While you could implement the matching using Bloom filters (as the browser already does for checking malicious URLs), I don't think it needs to be complicated. For example, I believe you could have an array of [events.UrlFilter](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/events/UrlFilter) using *urlMatches*() or *hostMatches*().

I get that detecting aspect ratio is impossible without inspecting the video stream. That's why I'm hoping this feature (per site settings) will be implemented. Thanks!
