### ISSUE TITLE
Disable Stretch

### ISSUE THREAD

**Issue by TwoPlayer** [dvlden/ultrawideo#49]
Hello,

is it possible ot get a) an option to diable the scretch mode or b) to get the possibility to toggle each mode with it on shortcut?

The reason behind this is, I don't want videos to be scretched, only to be upscaled and always toggling between all 3 modes is a bit anoying.

Thanks for consideration,
Simon

**Comment by dvlden** [comment]
Hello Simon,

At the moment the extension just cycles through currently active mode to the next and when comes to the last one, jumps back to the first. 

Adding different logic now, would affect other active users and make everything confusing. 

Adding the option to make each mode inactive from the popup, may sound like a best option here. 

Then the only logic that'd need improvement is to check if mode is disabled and skip through it. 

I like the idea and I'll mark this as help needed. Maybe someone can tackle it quickly, instead of me.
