### ISSUE TITLE
Not Working On HBOMAX Anymore

### ISSUE THREAD

**Issue by arzezio7** [dvlden/ultrawideo#55]
### Picture Does Not Scale Well on HBO MAX 
Scaling broke recently when playing content on HBO MAX

### Reproduction steps
Changing modes by pressing the hotkeys (Ctrl + X, Ctrl + Z)

### Expected behavior
Scaling should work fine

### Environment
- **OS**: Windows 10 21H1
- **Browser**: Edge 93.0.961.38

![image](https://user-images.githubusercontent.com/89209677/132445879-d3f707a1-8eda-47f0-8e0c-3d435580e43a.png)

**Comment by dvlden** [comment]
@arzezio7 Hello, HBO-MAX is not available in my country:
https://help.hbomax.com/us/Answer/Detail/000001289

I might be able to use VPN (unless they have detection for it), but I'd need an account to access. 
I tried on HBO-GO which is available in my region and I have a friend's account, but it works perfectly fine there, so I can't reproduce the problem to fix it.

Mind reaching out to me and send me account credentials and country that I should use to log-in from?

Kind regards.

**Comment by arzezio7** [comment]
Hi.
Here is the access details for the site:
HBO MAX
Email: ***@***.*** : arzcreed88Country : United States
- Aaroz Ezio - 

-Nothing is true, everything is permitted-
 

    On Friday, 10 September 2021, 04:38:35 am MYT, Nenad Novaković ***@***.***> wrote:  
 
 


@arzezio7 Hello, HBO-MAX is not available in my country:
https://help.hbomax.com/us/Answer/Detail/000001289

I might be able to use VPN (unless they have detection for it), but I'd need an account to access.
I tried on HBO-GO which is available in my region and I have a friend's account, but it works perfectly fine there, so I can't reproduce the problem to fix it.

Mind reaching out to me and send me account credentials and country that I should use to log-in from?

Kind regards.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dvlden** [comment]
Hello @arzezio7, I will delete your comment as this is not where you're supposed to share your credentials.

Aside, GitHub has masked your email and I can't see it. 

Please send me your credentials via e-mail to: 
`n.dvlden@gmail.com`

**Comment by dvlden** [comment]
Thank you @arzezio7 for the credentials.

I tested [HBOMAX](https://hbomax.com) in _Firefox v92.0_ and _Edge v93.0.961.47_ on _macOS Big Sur_, and it worked fine in both browsers. You can find the attached video where I showcase it.

Since you are on Windows, if it doesn't work on other platforms either, you could be having the following problem #46 which contains a solution by Tamius Han https://github.com/dvlden/ultrawideo/issues/46#issuecomment-830452888

Other problem that may be is some other extension interference with UltraWideo, if you have any other installed?

Let's see if we can solve the issue you're having...

https://user-images.githubusercontent.com/3460368/133005181-7eb45397-a0ce-4ef4-845e-4c393df7291a.mp4

**Comment by arzezio7** [comment]
Problem marked as solved using the suggested solution. Thank you very much for the help

**Comment by dvlden** [comment]
Glad it worked! Enjoy your HBO now 👍
