### ISSUE TITLE
chrome extension shortcut keys issues

### ISSUE THREAD

**Issue by envizion** [dvlden/ultrawideo#6]
the shortcut keys for the chrome extension doesn't work consistently. it seems to work on the session where i set the custom shortcut key but it doesn't work most of the time after chrome has been closed and reopened. the menu display my custom shortcut keys for toggling between mode correctly but just doesn't seem to toggle.

also a small quality of life request, when shortcuts does work, i have to release all combination of keys each time to toggle between modes.

for example: toggle shortcut set to ctrl+alt+c. holding down ctrl+alt and tapping c won't cycle between modes. it requires releasing all three keys and pressing them again to toggle the mode once each time.

**Comment by dvlden** [comment]
It'd be great if you kept the template given and wrote below each title whatever was asked.
But I understood what you said and I looked into this issue right away.

The problem of shortcuts (defaults and customized) stop working after browser restart has been resolved and I'll push it very shortly. Afterwards it'll be added to the extension stores of the supported browsers and you'll get automatic update.

Your second issue report of being unable to hold (e.g. `CTRL + SHIFT`) and toggle `ARROW UP` to toggle between modes does not appear to exist on my end.

What I'd suggest... Go to `chrome://extensions/` or if other browser... the extension manager...
Reload the **UltraWideo** extension and try to use default shortcuts and/or try to define custom ones different from `CTRL + ALT + C`, because that might be used for something else and it is preventing the toggle for extension (another browser extension/app or OS app). Don't know what else could cause the issue.

Thank you for this report.
