### ISSUE TITLE
Does this not crop?

### ISSUE THREAD

**Issue by KoB-Kirito** [dvlden/ultrawideo#64]
### Describe the bug
The video is 16:9 and the screen is 16:9, but the actual video is 21:9. So I want to zoom/crop to remove the black bars. But nothing happens.

### Reproduction steps
Example video.
https://www.youtube.com/watch?v=UOxkGD8qRB4

### Expected behavior
Black bars go poof.

### Environment
- **OS**: Win 10
- **Browser**: Firefox 93.0

**Comment by dvlden** [comment]
Hello @KoB-Kirito, thank you for reporting-in. 
Since you're on Windows, I'm assuming you're having the problem that everyone on Windows does...

Here's a screenshot from my Macbook Pro 13" where the video upscale works as expected.
<img width="1440" alt="Screen Shot 2021-11-04 at 21 08 01" src="https://user-images.githubusercontent.com/3460368/140412469-b30234af-31c1-4d59-b77a-4518cf5b1f97.png">

Check this and let me know:
https://github.com/dvlden/ultrawideo/discussions/62

**Comment by KoB-Kirito** [comment]
I see. I‘m on firefox though.

**Comment by dvlden** [comment]
Oh... I hope it's not happening on Firefox for Windows now too. I am on Firefox as well, but macOS.

**Comment by trimechee** [comment]
Hello, Ultrawideo in amazing and wonderful and very useful, thank you very much !     
 Recently I have tried Ultrawideo with ungoogled chromium browser but it doesn't work...I knwo Uungoogled chromium isn't supported browser by Ultrawideo, but i have tried your advise and I go to chrome://flags/ ANGLE graphics backend D3D9, and it worked perfectly ! the black borders have disappeared from my streaming video !

I think this tip is very important for wide compatibility with chromium based browsers other than chrome and edge, I would like to say that it will be better if in the description of Ultrawideo and in the chrome store and microsoft edge store, the users see a notice written in bold and in large font that it is necessary to enable ANGLE graphics backend D3D9 for compatibility with chromium browsers other than chrome and microsft edge !                
Thank you very much :)

**Comment by dvlden** [comment]
I'll consider writing this and other tips in the official extension website, when the time comes. 
I have plans for v3 to rewrite from scratch, but it's going to take time. 

Kind regards and enjoy!

**Comment by trimechee** [comment]
Great ! that's amazing, thank you  :) I used to download my videos from streaming sites and sometimes the episodes are boring and it's tedious to download so I started to watch the streaming videos through the web browser but there were those annoying black borders but with the magnificent Ultrawideo, this problem is solved !
Thank you again Mr Nenad, we are very grateful fot this marvelous wonderful work of art and technological gem
