### ISSUE TITLE
Time lapse interval verification

### ISSUE THREAD

**Issue by trimechee** [dvlden/ultrawideo#88]
Hello, sometimes the battery gets low and so we have to disable such and such a program, and I was wondering what was the energy and cpu usage made by our beloved extension Ultrawideo? they probably use a small amount of power but I would like to ask questions please, I noticed that when I pause Ultrawideo or I disable the extension, the stretch and the upscale of the video disappears, however I remember having tried another extension which stretches the video and when I disable the extension, the stretch of the video is preserved even though the extension is deactivated, does Ultrawideo check the stretch and the upscale of the video frequently?

Is there a possibility to keep the stretch in the video of the active tab even after disabling the extension?
it will be wonderful to implement such an option please  !

also it will be great to add option to control time lapse interval of verification of the aspect ratio, for example every 60 seconds or every 10 minutes in order to preserve the battery, thank you very much !

**Comment by dvlden** [comment]
Hello, 

Disabling the extension will remove all of its functionality, including what it previously did to a video element.
This will likely change in the future and disable option will go away, as it's not very useful since the browser itself provides the option to disable any extension.

Your battery is safe with this extension, nothing to worry about.

Kind regards.

**Comment by trimechee** [comment]
Interesting, thank you :)
